---
  - name: Install php-fpm
    apt:
      name: php{{ php_fpm_version }}-fpm
      state: present
    notify: restart php-fpm

  - name: Create php.ini files
    template:
      src: php.ini.j2
      dest: /etc/php/{{ php_fpm_version }}/fpm/php.ini
    notify: restart php-fpm
