---
- hosts: all
  gather_facts: False
  become: yes
  vars:
    nginx_remove_default_vhost: true
    ssl_certs_domains: [ilia.devops.srwx.net]
    ssl_certs_email_confirmation: ilia@ilin.dn.ua
  pre_tasks:
    - name: Install python for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when: output.stdout != ""
    - name: Gathering Facts
      setup:
  roles:
    - geerlingguy.nginx
    - ssl_certs
    - {role: calc-web, tags: web}

# - hosts: goapp
#   tasks:
#   - name: Install packages
#     apt: name={{ item }} state=latest
#     with_items:
#       - nginx
#       - letsencrypt
#       - php-fpm
#       - git
#
#   - name: Remove nginx default config
#     file: path=/etc/nginx/sites-enabled/default state=absent
#     notify: restart nginx
#
#   - name: Add folder for SSL chalenge
#     file: path=/opt/acme state=directory
#
#   - name: Create site ilia.devops.srwx.net minimal configuration
#     template:
#       src=ilia.devops.srwx.net-base.conf.j2
#       dest=/etc/nginx/sites-available/ilia.devops.srwx.net.conf
#       owner=root
#       group=root
#       mode=0644
#     notify: restart nginx
#
#   - name: Installing ilia.devops.srwx.net configuration
#     file:
#       path=/etc/nginx/sites-enabled/ilia.devops.srwx.net.conf
#       src=/etc/nginx/sites-available/ilia.devops.srwx.net.conf
#       state=link
#     notify: restart nginx
#     register: minimal_nginx_config
#
#   - name: Force nginx reloads
#     meta: flush_handlers
#     when: minimal_nginx_repo=https://github.com/bkmz/goapp-web
#       dest=/opt/goapp-webconfig.changed
#
#   - name: Recieve SSL sertificates
#     raw: letsencrypt certonly --non-interactive --agree-tos --webroot -w /opt/acme -d ilia.devops.srwx.net --email ilia@ilin.dn.ua
#     when: minimal_nginx_config.changed
#
#   - name: Chage site ilia.devops.srwx.net configuration
#     template:
#       src=ilia.devops.srwx.net.conf.j2
#       dest=/etc/nginx/sites-available/ilia.devops.srwx.net.conf
#       owner=root
#       group=root
#       mode=0644
#     notify: restart nginx
#
#   - name: Deploy goapp-web
#     git:
#       repo=https://github.com/bkmz/goapp-web
#       dest=/opt/goapp-web
#
#   - name: Clone goapp repository
#     local_action: git
#       repo=https://github.com/bkmz/goapp.git
#       dest=temp/goapp
#       version=api
#
#   - name: Create folder for goapp
#     file:
#       path=/opt/goapp state=directory owner=www-data group=www-data mode=755
#
#   - name: Deploy goapp binaries
#     copy:
#       src=temp/goapp/main
#       dest=/opt/goapp/main
#       owner=www-data
#       group=www-data
#       mode=755
#
#   - name: Installing goapp service
#     copy:
#       src=temp/goapp/goapp.service
#       dest=/etc/systemd/system/goapp.service
#     notify:
#       - reload systemd
#       - clear temp files
#
#     register: goapp-service
#
#   - name: Reload systemd
#     meta: flush_handlers
#     when: goapp-service.changed
#
#   - name: Start goapp servive
#     service: name=goapp enabled=yes state=started
#
#   - name: Deploy phpapp
#     git:
#       repo=https://github.com/bkmz/phpapp.git
#       dest=/opt/phpapp
#
#   handlers:
#     - name: restart nginx
#       service: name=nginx state=restarted
#
#     - name: reload systemd
#       command: systemctl daemon-reload
#
#     - name: clear temp files
#       local_action: file state=absent path=temp/
